spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yandex_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    bootstrap-servers: ${KAFKA-BROKERS:localhost:9092}
    listener:
      ack-mode: record
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 2147483647
        transactional.id: yandexTracker
    consumer:
      autoOffsetReset: earliest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      isolation-level: read_committed

      properties:
        spring.json.trusted.packages: "com.modula.common.domain.workflow.execution.events"

kafka:
  topics:
    workflow-executor-topic: exec-topic

yandex:
  tracker:
    api:
      base-url: https://api.tracker.yandex.net/v2
